// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT_41tCiH5PYG2f7A5Rs86lSxINJRpI_k',
    appId: '1:323268556553:web:a41a0c03e5b59d919385d8',
    messagingSenderId: '323268556553',
    projectId: 'yenkhanh-next25',
    authDomain: 'yenkhanh-next25.firebaseapp.com',
    storageBucket: 'yenkhanh-next25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcT7eZJobl0VvH1aEQ1HtaIDKh2hk9Ws',
    appId: '1:323268556553:android:d45bef5e88a71ed89385d8',
    messagingSenderId: '323268556553',
    projectId: 'yenkhanh-next25',
    storageBucket: 'yenkhanh-next25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5aQ-fUgsafeiNaG0J6WygUcsqp1hlL7E',
    appId: '1:323268556553:ios:d7fd690b3f3b4cb59385d8',
    messagingSenderId: '323268556553',
    projectId: 'yenkhanh-next25',
    storageBucket: 'yenkhanh-next25.firebasestorage.app',
    iosBundleId: 'com.example.next25Demo',
  );
}
