// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeslzXMJOcRW77BV-5XYTJWJ0D-00hCq8',
    appId: '1:1025902230344:web:eb9ca50d538d3419b6117d',
    messagingSenderId: '1025902230344',
    projectId: 'compass-ios-455022',
    authDomain: 'compass-ios-455022.firebaseapp.com',
    storageBucket: 'compass-ios-455022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5s-frlzmlN8xRuClgdZPJ00HKZVgBd7A',
    appId: '1:1025902230344:android:5623a28d48302226b6117d',
    messagingSenderId: '1025902230344',
    projectId: 'compass-ios-455022',
    storageBucket: 'compass-ios-455022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYizz-a19MKGTS_hrZtOcQPrU7PpzlwQ',
    appId: '1:1025902230344:ios:a0ce366519e0fc27b6117d',
    messagingSenderId: '1025902230344',
    projectId: 'compass-ios-455022',
    storageBucket: 'compass-ios-455022.firebasestorage.app',
    iosBundleId: 'com.example.cupertinoCompass',
  );
}
