const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
const OPEN_WEATHER_API_KEY = process.env.OPEN_WEATHER_API_KEY;
const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY;

export { GOOGLE_API_KEY, OPEN_WEATHER_API_KEY, UNSPLASH_ACCESS_KEY };